FROM registry.redhat.io/ubi9/go-toolset@sha256:35f08031de19eb51d6b35ed62c6357d3529bc69a8db65cf623ea5f0b44051999 AS builder
USER root
WORKDIR /go/src/github.com/brancz/kube-rbac-proxy
COPY . .
ENV GO111MODULE=on
# vendor/ is not committed; generate it at build time
RUN go mod vendor
ENV GOFLAGS="-mod=vendor -tags=strictfipsruntime"
ENV GOEXPERIMENT=strictfipsruntime
ENV CGO_ENABLED=1
ARG TARGETARCH
RUN GOOS=linux VERSION=$(cat VERSION) GOARCH=${TARGETARCH} make build && \
    cp _output/kube-rbac-proxy-linux-${TARGETARCH} _output/kube-rbac-proxy

FROM registry.redhat.io/ubi9/ubi-minimal@sha256:7d4e47500f28ac3a2bff06c25eff9127ff21048538ae03ce240d57cf756acd00

ARG FROM_DIRECTORY=/go/src/github.com/brancz/kube-rbac-proxy
COPY --from=builder ${FROM_DIRECTORY}/_output/kube-rbac-proxy  /usr/bin/kube-rbac-proxy

RUN mkdir -p /licenses
COPY --from=builder ${FROM_DIRECTORY}/LICENSE /licenses/LICENSE.kube-rbac-proxy.txt

USER 65534
EXPOSE 8080
ENTRYPOINT ["/usr/bin/kube-rbac-proxy"]

LABEL com.redhat.component="odh-kube-rbac-proxy-rhel9" \
      name="managed-open-data-hub/odh-kube-rbac-proxy-rhel9" \
      io.k8s.description="This is a proxy, that can perform Kubernetes RBAC authorization." \
      summary="odh-kube-rbac-proxy" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-kube-rbac-proxy" \
      io.k8s.description="odh-kube-rbac-proxy" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
